### ISSUE TITLE
The cloudbase-init service terminated unexpectedly

### ISSUE THREAD

**Issue by gedOHub** [cloudbase/cloudbase-init#103]
Is this normal practice that cloudbase-init service terminates unexpectedly?
In event viewer I see errors like this:
"The cloudbase-init service terminated unexpectedly.  It has done this 1 time(s)."
````
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7034</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2017-11-03T09:28:38.342181100Z" /> 
  <EventRecordID>17987</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="612" ThreadID="1848" /> 
  <Channel>System</Channel> 
  <Computer>VM-515efd28-d95</Computer> 
  <Security /> 
  </System>
<EventData>
  <Data Name="param1">cloudbase-init</Data> 
  <Data Name="param2">1</Data> 
  <Binary>63006C006F007500640062006100730065002D0069006E00690074000000</Binary> 
  </EventData>
  </Event>
````
Cloudbase-init service is running on Windows Server 2016 standard

**Comment by rainmanh** [comment]
@gedOHub , I got the exact problem as yourself.
Last night I was raising the following : https://ask.cloudbase.it/question/2554/windows-2016-the-application-specific-permission-settings-do-not-grant-local-activation-permission/

I have tried so many different things, but the service keeps dying a after a little while for the same reason.

**Comment by ader1990** [comment]
@rainmanh you have a different issue altogether. @gedOHub can you close this issue, as per your ask response, it has been solved by setting the proper cloudbase-init configs.

**Comment by ader1990** [comment]
@rainmanh can you open a new issue with your problem and put there the steps you have followed when creating the image? You can also check an automated tool to create the Windows image: https://github.com/cloudbase/windows-openstack-imaging-tools . I suggest you to use the experimental branch.

Thank you,
Adrian Vladu

**Comment by rainmanh** [comment]
Apologies @ader1990 , will do that.

**Comment by gedOHub** [comment]
Answer can be found here: https://ask.cloudbase.it/question/2541/why-cloudbase-init-service-exits-unexpectedly/

**Comment by gedOHub** [comment]
Answer can be found: https://ask.cloudbase.it/question/2541/why-cloudbase-init-service-exits-unexpectedly/
