### ISSUE TITLE
Error when setting instance-id to integer

### ISSUE THREAD

**Issue by blitztide-htb** [cloudbase/cloudbase-init#124]
Cloudbase init fails to run,
Crashes saying that "str" and "int" cannot be concatenated.
Will work if instance-id has a quoted integer.

**Comment by ader1990** [comment]
Hello,

Instance-id, as the name is concerned, is a unique identifier that historically, was a string. An integer to string cast would be in order, if it is required. Can you please provide some information on your use-case, if possible?

Thank you,
Adrian
