### ISSUE TITLE
Cloudbase Init 1.1.4 does not install on Windows 7 or Server 2008 R2

### ISSUE THREAD

**Issue by gr4ytech** [cloudbase/cloudbase-init#138]
I recently tried to install Cloudbase Init on Windows 7 and Server 2008 R2 for our cyber range and got the error below:

![api-ms-win-core-path-l1-1-0.dll is missing from your computer](https://github.com/cloudbase/cloudbase-init/assets/48267081/b60f5f39-fd11-4585-8fec-03a8db26b29d)

This seems to be based on an error where Cloudbase Init tries to install or use Python 3.9 which is not supported by Windows 7/Server 2008. It looks like Python 3.8 should be supported and is by the [cloudbase-init python package](https://pypi.org/project/cloudbase-init/).

What would be the appropriate course of action for Cloudbase Init to properly install on these OS platforms?

**Comment by ader1990** [comment]
Hello,

Firstly, Windows 7/Windows Server 2008 R2 are no longer supported by Microsoft or Python community.
I think you might be able to use an older version of the installer if you have all the latest updates installed on Win7/2008 R2.

1.1.4 installer uses Python 3.10 and latest installer uses Python 3.11 https://github.com/cloudbase/cloudbase-init-installer.
You can check the https://github.com/cloudbase/cloudbase-init/releases page and try with an older version of the installers.

Python 3.8 is no longer maintained, but the installer can be changed if it is needed. Please let us know if there is a need for it.

Thank you,
Adrian Vladu

**Comment by gr4ytech** [comment]
Hi Adrian,

Yes, I understand that Windows 7/ Server 2008 is not supported by Microsoft. The goal of our cyber range is to get people exposure to legacy operating systems that are still found in industry and how to defend against such attacks.

I've confirmed that version 1.1.2 and below work properly with 2008/Windows 7 images. So I'll close this issue. Thanks!
