### ISSUE TITLE
version 1.0 binaries?

### ISSUE THREAD

**Issue by rgl** [cloudbase/cloudbase-init#16]
When I go to https://cloudbase-init.readthedocs.io/ I see "cloudbase-init 1.0 documentation", but https://github.com/cloudbase/cloudbase-init/releases has no 1.0 version. What am I missing?

**Comment by ader1990** [comment]
@rgl the update to show the correct version in the readthedocs page is under way:
https://review.opendev.org/#/c/694535/

**Comment by ader1990** [comment]
@rgl the docs have been updated for the latest version (I cannot update the previous docs, because it would break the mutability of docs). https://cloudbase-init.readthedocs.io/en/latest/
When 0.9.12 version is released, the stable docs will change to the current latest docs.

**Comment by ader1990** [comment]
@rgl this issue has been fixed by https://github.com/cloudbase/cloudbase-init/commit/e74570e01e219a7e246161ba76a3c53bb1a65293

If all good, can you please close this issue?
