### ISSUE TITLE
versioned binaries?

### ISSUE THREAD

**Issue by rgl** [cloudbase/cloudbase-init#17]
Can you start publishing versioned binaries at https://github.com/cloudbase/cloudbase-init/releases?

**Comment by ader1990** [comment]
Currently, the MSI installers are published in a stable/nightly build format:
Stable
(64bit) https://www.cloudbase.it/downloads/CloudbaseInitSetup_Stable_x64.msi
(32bit) https://www.cloudbase.it/downloads/CloudbaseInitSetup_Stable_x86.msi

Beta
(64bit) https://www.cloudbase.it/downloads/CloudbaseInitSetup_x64.msi
(32bit) https://www.cloudbase.it/downloads/CloudbaseInitSetup_x86.msi

https://github.com/cloudbase/cloudbase-init#downloads

**Comment by rgl** [comment]
Indeed, those are clearly mentioned on the documentation, but that's not what I was really asking for :-)

From a user standpoint, it would be easier (or normal for a project hosted in github) to have the artifacts in this project release page. The release page is more explicit about the binaries as they will have a dedicated page per release/version and we can easily download any version from a stable / versioned URL.

**Comment by ader1990** [comment]
As this is Python project, you can run the code directly if you have a Python environment. 
I understand what you are asking, only that the process of creating the MSI installer is not that straightforward. I suppose the GitHub actions environment can allow such a build in the future, at least for the newer releases.

This is the installer code, in case you ever need to build your own installer: https://github.com/cloudbase/cloudbase-init-installer

**Comment by alexpilotti** [comment]
Hi @rgl, added them for 0.9.11 and we'll keep doing so moving forward. Thanks for bringing this up!
