### ISSUE TITLE
Use local files instead of downloading

### ISSUE THREAD

**Issue by harmw** [cloudbase/cloudbase-init#23]
Hi,

Currently cloud-init downloads all required zipfiles and scripts during the process. I'd like to be able to download everything in advance and inject the lot in the iso image i'm using (I'm using oz to create images: https://github.com/clalancette/oz).

I'm injecting PSWindowsUpdate.zip to c:\windows\temp\ though after booting up the vm it prints the following error in the launched powershell window:

 System.IO.IOException: Not enough permission to perform operation.

Logon.ps1 is modified to use the new file location to where the file was injected:
$psWindowsUpdatePath = "$ENV:SystemRoot\temp\PSWindowsUpdate.zip"

Why doesn't this work as expected?

**Comment by alexpilotti** [comment]
Hi @harmw, we have a separate project for generating Windows images, more appropriate IMO for this context:

https://github.com/cloudbase/windows-openstack-imaging-tools

External downloads have been eliminated. Our main focus is to eliminate /limit the need to run Windows updates online and slipstream them offline if possible.

Note: The Cloudbase-Init project has been moved to StackForge and issues are currently being managed with launchpad.
