### ISSUE TITLE
Windows VM unable to get IP address from net with  --flat_injected=True in nova.conf

### ISSUE THREAD

**Issue by mcorvalan** [cloudbase/cloudbase-init#32]
Hi ALl:
I'm sending this post to ask you:
I have running the Essex version for OpenStack with Flat-network with --flat_injected=True.
I could launch Windows instance in my Essex openStack, with Cloud-init cloudBase.
But I see the ipconfig I see 172.16.191.20 and the network is 10.32.156.0.
I installed in the windows image the Cloud-init cloudBase but I dont know why the instance can't get the Ip network (10.32.156.0) for windows.
------------------------
This is my nova.conf

--auth_strategy=keystone
--cc_host=10.32.156.5
--connection_type=libvirt
--dhcpbridge_flagfile=/etc/nova/nova.conf
#--dhcpbridge=nova-dhcpbridge
--dhcpbridge=/usr/bin/nova-dhcpbridge
--ec2_host=10.32.156.5
--ec2_private_dns_show_ip
--ec2_url=http://10.32.156.5:8773/services/Cloud
--fixed_range=10.32.156.0/24
--flat_injected=True
#--force_dhcp_release
--glance_api_servers=essexglance.melicloud.com:9292
--image_service=nova.image.glance.GlanceImageService
--iscsi_helper=tgtadm
--libvirt_use_virtio_for_bridges
--lock_path=/var/lock/nova
--logdir=/var/log/nova
--network_manager=nova.network.manager.FlatManager
--network_size=256
--nova_url=http://10.32.156.5:8774/v1.1/
--osapi_host=10.32.156.5
--rabbit_host=10.32.156.5
--rabbit_port=5672
--root_helper=sudo nova-rootwrap
#--routing_source_ip=10.32.156.5
#--s3_host=10.32.156.5
--sql_connection=mysql://nova:notnova@galera.melicloud.com/DC4_r62
--state_path=/var/lib/nova
--verbose
--vncserver_listen=0.0.0.0
--allow_resize_to_same_host=True
--libvirt_xml_template=/etc/nova/libvirt.xml.template
--compute_scheduler_driver=nova.scheduler.filter_scheduler.FilterScheduler
--scheduler_default_filters=RamFilter,ComputeFilter

# DANGER : TURNING THIS ON, COULD REBOOT INSTANCES WHEN YOU RESTART NOVA COMPUTE
--start_guests_on_host_boot=False
--resume_guests_state_on_host_boot=True
--reserved_host_memory_mb=20480

I launched with this option with Linux image and it's working very well.
But now I'm testing  with windows Image.

When I launch my windows instance created via this link (http://www.cloudbase.it/create-windows-openstack-images/)
I can see the instance is created  but the IP that It received it's no from this net.
For example:
I launch a instance with the 10.32.x.x net, I can see the ip that gives nova is ok (same net),
But when I  connect via vnc to see the IP is 172.16.191.20 and so I gotta put the correct ip manually.
after this way I can connect via rdp  later.

I need to know How can I correct this error in Essex with " --flat_injected=True" in nova.

I'll add more info.
I did this test (windows image) with Grizzly and with dchp option, and the Windows instance was launched very well.
With its IP corresponding  to the same net.

Thanks in advance.

**Comment by alexpilotti** [comment]
Hi @mcorvalan, Cloudbase-Init has been moved to Stackforge with issues bring tracked on launchpad. Static network support is currently being refactored, please let me know if you still experience this issue.

Thanks
