### ISSUE TITLE
Windows Server 2019 with Cloudbase-init Keeps Rebooting after Provisioning

### ISSUE THREAD

**Issue by vmwarelab** [cloudbase/cloudbase-init#37]
Hello

I have prepared a Windows Server 2019 Template with Cloudbase-init on vSphere. and currently after provisioning the VM, it keep rebooting in a continuous loop . 

Even if I convert the template that I prepared back to a VM and  boot it up i m seeing the same thing.

Wondering if anyone seen this behaviour or know if Windows Server 2019 is even supported

**Comment by ader1990** [comment]
Hello,

Cloudbase-Init is supported for Windows Server (any version). Can you please check that you are using the latest version of Cloudbase-Init?

Also, can you provide the steps that you followed to create the image?

Thank you,
Adrian Vladu

**Comment by vmwarelab** [comment]
i am using the latest 64Bit stable build from this GitHub repo.
The steps i took is very simple

Build a windows 2019 from an ISO
Disabled firewall , Set time zone, enabled remote desktop, etc
installed cloud base init and configured the configuration files
Sysprep and shutdown

Followed the steps mentioned here https://blogs.vmware.com/management/2019/11/cloudbase-init-windows-initialization.html

**Comment by ader1990** [comment]
@vmwarelab got it. The tutorial you mentioned is not clear enough on the actual installer version to use (all you have there is 'Ensure you are using version 0.9.12.dev72 or greater').

Currently, the stable release has Cloudbase-Init version 0.9.11 which does not include the OvfService service and the boot will fail as it expects cloudbase-init to run correctly during Sysprep specialize stage.

Please use the beta installer from https://www.cloudbase.it/downloads/CloudbaseInitSetup_x64.msi installer and try again.

**Comment by vmwarelab** [comment]
That the same link i used and i did this twice already..  is the link provided is actually different ?

![image](https://user-images.githubusercontent.com/19843322/75041214-215a2f80-548a-11ea-90a5-5d74d741d13c.png)

**Comment by ader1990** [comment]
Note that you have to use the beta installer: https://www.cloudbase.it/downloads/CloudbaseInitSetup_x64.msi

```diff
stable: https://www.cloudbase.it/downloads/CloudbaseInitSetup_Stable_x64.msi -> no Ovf support
beta:   https://www.cloudbase.it/downloads/CloudbaseInitSetup_x64.msi -> Ovf is supported
```

**Comment by vmwarelab** [comment]
ahhh okay .. i will give it a shot and report back here .

**Comment by vmwarelab** [comment]
That worked. I have another issue i want to tackle and that is using a static Ip assignment instead of DHCP IP assignment which what i used for now but i will open another ticket for it when the time comes.. Thank you so much for helping out @ader1990
