### ISSUE TITLE
MSIs for v1.1.0?

### ISSUE THREAD

**Issue by rhockenbury** [cloudbase/cloudbase-init#39]
Can the MSIs for the v1.1.0 release be added to the release artifacts?

**Comment by ader1990** [comment]
The installers are to be published soon.

**Comment by alexpilotti** [comment]
MSIs published, the download urls are up to date:

https://cloudbase.it/downloads/CloudbaseInitSetup_Stable_x64.msi
https://cloudbase.it/downloads/CloudbaseInitSetup_Stable_x86.msi
