### ISSUE TITLE
MSI install (Upgrade) gives Error: Failed to install:  Another version of this product is already installed

### ISSUE THREAD

**Issue by hatvik** [cloudbase/cloudbase-init#43]
Trying to automate install of new versions fails
`C:/Windows/Temp/CloudbaseInitSetup_1_1_0_x64.msi /qn`

> Error: Failed to install:  Another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel.

Please make the msi remove the old version automatically

**Comment by ader1990** [comment]
Hello,

This error usually happens when you try to upgrade to another non-incremental version.

You can easily add an uninstall step in your workflow in PowerShell like this:

```powershell
(Get-WmiObject win32_product | Where-Object {$_.Name -like "*cloudbase*"}).Uninstall()
```

**Comment by alexpilotti** [comment]
Hi, Closing this as this comes from the installer, so it needs to be filed here: https://github.com/cloudbase/cloudbase-init-installer

By default MSIs don’t allow same version upgrades, which happens with the continuous builds in between stable (tagged) releases.
