### ISSUE TITLE
cannot parse OpenNebula 5.12 metadata correctly

### ISSUE THREAD

**Issue by azarakko** [cloudbase/cloudbase-init#58]
exists empty string in OpenNebula 5.12.0.1 context.sh.
like this
~~~
ETH0_GATEWAY6=''
~~~

but not considered empty string current metadata parser.

https://github.com/cloudbase/cloudbase-init/blob/3c290194c139990f2a0e5747aa2f6c9554d26659/cloudbaseinit/metadata/services/opennebulaservice.py#L91-L96

in result cannnot parse Opennebula 5.12 metadata correctly.

sample context.sh
[context.txt](https://github.com/cloudbase/cloudbase-init/files/5184275/context.txt)

**Comment by ader1990** [comment]
Hello,

Regular expression are always a pain. Here is a potential fix for your issue, can you please try it out:

https://review.opendev.org/#/c/750219/

Currently, the cloudbase-init development is done on review.opendev.org, using gerrit.

Thank you,
Adrian Vladu

**Comment by azarakko** [comment]
I tried to apply fix.
the fix works fine.

Thank you.

**Comment by ader1990** [comment]
@azarakko great to hear that. 
I  would reopen the issue so that it gets closed when the patch is merged.
