### ISSUE TITLE
cloudbase-init on Windows 7 miss restart

### ISSUE THREAD

**Issue by ChrisBKK** [cloudbase/cloudbase-init#63]
Hello,
We created a Windows 7 Enterprise 64bit Image and installed the latest cloudbase-init msi.
At boot we see that the cloudbase-init script is running. But the hostname isn't set. When we start the cloudbase-init service manually the system restarts and the hostname is set properly. 

On Windows 2012 Server we have no issues.

**Comment by ociuhandu** [comment]
Since the project is moved to StackForge, we are going to mark the issue as closed here.
