### ISSUE TITLE
Can cloudbase open how to build binary package from source?

### ISSUE THREAD

**Issue by silenceli** [cloudbase/cloudbase-init#65]
I think cloudbase-init is a great open source project.
sometimes I still need to add/modify some features. I don't known how to build the binary package from the source code. It is not very convenient for me.

I think the binary package has a lot difference with the source code. 

1. do you use py2exe to convert python to exe?
2. after install CloudbaseInitSetup_Beta_x64.msi, I found there is a service called Cloud Initialization Service in services.msc. Can you open how to write the windows service?
3. after install CloudbaseInitSetup_Beta_x64.msi, there is no cloudbase-init source code in the install path, but there has a python environment in the install path. My question is the cloudbase-init is convert to exe, do we need python environment?

hope for you response.
Thank you!

**Comment by ociuhandu** [comment]
At the moment the cloudbase-init project is entirely open sourced while the installer itself is not (although freely available of course).

Here's a simple way to provision a Windows image with your extensions and without a custom installer:

Install the current cloudbase-init using the installer
Update cloudbase-init, e.g. from a github fork with "python setup.py install"
Sysprep again the instance.

The project moved on StackForge, please file up bugs and blueprints on: https://launchpad.net/cloudbase-init

**Comment by silenceli** [comment]
Thanks you
