### ISSUE TITLE
UserData plugin run before SetupUserPassword & SshPublicKeys 

### ISSUE THREAD

**Issue by dieu** [cloudbase/cloudbase-init#67]
Hello @alexpilotti,

We do bootstrap Windows vm on OpenStack IceHouse. 

Startup order of plugins to be a problem now for us. 

Would be better if the order was as follows: 
* SetupUserPassword 
* UserData / UserDataScripts 
* SshPublicKeys

**Comment by ociuhandu** [comment]
Since the project is moved to StackForge, we are going to mark the issue as closed here.
