### ISSUE TITLE
vmwareguestinfo service: Static network assignment

### ISSUE THREAD

**Issue by gadekalp** [cloudbase/cloudbase-init#70]
Hi,

Is there any way to assign static networking to VM using vmwareguestinfo service as it is not listed under available services?

https://cloudbase-init.readthedocs.io/en/latest/services.html#vmware-guestinfo-service

**Comment by ThomasSchoeller** [comment]
Hey @gadekalp,

Does it work and the documentation is only not correct?

Thank you
