### ISSUE TITLE
hostname '-' is replaced to '0'

### ISSUE THREAD

**Issue by wywself** [cloudbase/cloudbase-init#72]
hello, 

the code `hostname = re.sub(r'-$', '0', hostname)` in cloudbase-init/utils/hostname.py will replace the last '-' to '0', What does this substitution mean? why is this necessary？

![image](https://user-images.githubusercontent.com/8843053/126099671-dbd3484d-5b6a-4737-9bdb-17ff497ee6b0.png)

Can someone help me please？
Thank you.

**Comment by ader1990** [comment]
Hello,

According to https://datatracker.ietf.org/doc/html/rfc952, the hostname cannot end with a hyphen (can be a digit or a letter).
At the time of the change, replacing the hyphen with a digit or a letter made sense.

Do you have an issue caused by this substitution?

Thank you,
Adrian Vladu
