### ISSUE TITLE
Change the execution order of the plugins so that UserDataPlugin is executed last

### ISSUE THREAD

**Issue by ader1990** [cloudbase/cloudbase-init#75]
As the userdata scripts can interfere with other cloudbaseinit plugins, it is preferable to have all the other plugins executed before the start of the UserDataPlugin.

One other reason is that the userdata plugins can contain logic that is based on the other plugins.

Furthermore, the logic in the userdata cannot be foreseen. For example, if the userdata code contains logic for a domain controller installation, the SetUserPasswordPlugin and ConfigWinRMListenerPlugin will fail. The user password expiration cannot be set, as .the "Admin" user is not a local user anymore, it is a domain one(possible quickfix: https://github.com/ionutbalutoiu/cloudbase-init/commit/2275d9eb5d6c83b5775e369c41c6c3385483b876).

**Comment by ociuhandu** [comment]
Since the project is moved to StackForge, we are going to mark the issue as closed here.
