### ISSUE TITLE
Add a retry for default gateway retrieval

### ISSUE THREAD

**Issue by ader1990** [cloudbase/cloudbase-init#76]
If the network stack is not fully initialized when the default gateway is retrieved, the gateway will be None.

Solution: add a retry for the gateway retrieval, here:
https://github.com/cloudbase/cloudbase-init/blob/master/cloudbaseinit/utils/network.py#L54

This is very important, as the http metadata service will post the "Admin" user password to the metadata service and thus making the password accessible to the user.

**Comment by ociuhandu** [comment]
Since the project is moved to StackForge, we are going to mark the issue as closed here.
