### ISSUE TITLE
Failed to set administrator password for windows 2019 English version

### ISSUE THREAD

**Issue by ziguang1** [cloudbase/cloudbase-init#92]
hello,everyone,   
I'm doing it using cloudbase init
 Windows 2019 English initialization
The log shows that the setting was successful, but the login with the set password failed

help me! thank you?
[cloudbase-init.log](https://github.com/cloudbase/cloudbase-init/files/8488538/cloudbase-init.log)

**Comment by ziguang1** [comment]
close

**Comment by fbermel** [comment]
Hi @ziguang1, I'm having the same problem. Why did you just close this issue? What was your solution?

**Comment by ader1990** [comment]
Hello @KnappeGEIL,

By default, cloudbase-init administrator username that gets configured is called Admin (can be changed in the config file).

Do you a login problem with the user Administrator or Admin?

Here is the documentation: https://cloudbase-init.readthedocs.io/en/latest/plugins.html#setting-password-main .

Thank you,
Adrian

**Comment by fbermel** [comment]
Hi @ader1990,

thanks a lot for link that part of the documentation. I could resolve my problem with the help of it.

Best regards
Fabi
