### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by anantpatil** [cloudbase/cloudbase-init#94]
I want to use [Sourcegraph](https://sourcegraph.com) for cloudbase-init code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/cloudbase/cloudbase-init. (It should only take 30 seconds.)

Thank you!

**Comment by alexpilotti** [comment]
The official repo URL currently is on https://github.com/openstack/cloudbase-init
